
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.Random;
import java.util.Set;
import java.util.Stack;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dagom
 */
public class taquillaCine extends javax.swing.JFrame {

    ImageIcon indianajones, batman, avatar, tadeo, joker;
    Lista lista = new Lista();
    Cola cola = new Cola();
    Random random = new Random();
    pantallaCobro cobro = new pantallaCobro();
    Stack<ventasTotales> ventas = new Stack<>();

    
    public taquillaCine() {
        
        initComponents();
        indianajones = new ImageIcon("indianajones.jpeg");
        batman = new ImageIcon("batman.jpg");
        avatar = new ImageIcon("avatar.jpg");
        tadeo = new ImageIcon("tadeo.jpg");
        joker = new ImageIcon("joker.jpg");

        
       
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cartelera = new javax.swing.JPanel();
        peliculasComboBox = new javax.swing.JComboBox<>();
        horarioComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salaPane = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menorSpinner = new javax.swing.JSpinner();
        adultosSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        continuarButton = new javax.swing.JButton();
        totalPanel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ventasButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout carteleraLayout = new javax.swing.GroupLayout(cartelera);
        cartelera.setLayout(carteleraLayout);
        carteleraLayout.setHorizontalGroup(
            carteleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        carteleraLayout.setVerticalGroup(
            carteleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        peliculasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batman", "Avatar", "Indiana Jones", "Tadeo", "Joker" }));
        peliculasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculasComboBoxActionPerformed(evt);
            }
        });

        horarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00 p.m.", "4:00 p.m.", "6:20 p.m.", "8:40 p.m." }));
        horarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Sala asignada:");

        jScrollPane1.setViewportView(salaPane);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Boletos Menor de Edad:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Boletos Mayor de Edad:");

        menorSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menorSpinnerStateChanged(evt);
            }
        });

        adultosSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                adultosSpinnerStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Total:");

        continuarButton.setText("CONTINUAR");
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Pelicula:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Horario:");

        ventasButton.setText("VENTAS");
        ventasButton.setActionCommand("");
        ventasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ventasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(continuarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cartelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(peliculasComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adultosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(menorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peliculasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adultosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cartelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        // Anadir un elemento a la lista.
        String nombre = peliculasComboBox.getSelectedItem().toString();
        String horario = horarioComboBox.getSelectedItem().toString();
        String sala = salaPane.getText();
        int boletos = (Integer) menorSpinner.getValue() + (Integer) adultosSpinner.getValue();
        Double total = Double.valueOf((Integer) menorSpinner.getValue() * 5) + ((Integer) adultosSpinner.getValue() * 7.25);
        Double precioFinal = (total) + (total * 0.13);
       
        cobro.setTitle("Caja");
      
        //agrega la informacion y utiliza la cola para mantener orden en la fila.
        if(cobro.cola.cantidad() < 1) {
            
            //agregar a la lista
            lista.agregar(nombre, horario, sala, boletos, total);
            lista.imprimir();
            
            //agregar a la pila
            ventas.add(new ventasTotales(boletos, precioFinal));
            
            //agregar a la cola 
            cobro.cola.insertar(lista.orderNumber());
            cobro.ordernumPanel.setText(String.valueOf(lista.orderNumber()));
            cobro.cantPanel.setText(String.valueOf(boletos));
            cobro.totalOrden.setText(String.valueOf(precioFinal));
        } else {
            System.out.println(" ");
            System.out.println("Porfavor a esperar a que terminemos de procesar la siguiente transaccion. ");
        }

        cobro.setVisible(true);
        String control = "n";
        
        
        
      
        
        
        
    }//GEN-LAST:event_continuarButtonActionPerformed

 
    
    
    
    
    private void peliculasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculasComboBoxActionPerformed
        // TODO add your handling code here:
        String pSelected = peliculasComboBox.getSelectedItem().toString();
        
        if(pSelected == "Batman") {
            Graphics cartel = cartelera.getGraphics();
            batman.paintIcon(this, cartel, 0, 0);
        } if (pSelected == "Indiana Jones") {
            Graphics cartel = cartelera.getGraphics();
            indianajones.paintIcon(this, cartel, 0, 0);
        } if (pSelected == "Avatar") {
            Graphics cartel = cartelera.getGraphics();
            avatar.paintIcon(this, cartel, 0, 0);
        } if (pSelected == "Tadeo") {
            Graphics cartel = cartelera.getGraphics();
            tadeo.paintIcon(this, cartel, 0, 0);
        } if (pSelected == "Joker") {
            Graphics cartel = cartelera.getGraphics();
            joker.paintIcon(this, cartel, 0, 0);
        }
        
        
   
        
           
        
     
        
    }//GEN-LAST:event_peliculasComboBoxActionPerformed

    private void menorSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menorSpinnerStateChanged
        // TODO add your handling code here:
        Double total = Double.valueOf((Integer) menorSpinner.getValue() * 5) + ((Integer) adultosSpinner.getValue() * 7.25);
        totalPanel.setText("$ " + String.valueOf(total));
    }//GEN-LAST:event_menorSpinnerStateChanged

    private void adultosSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_adultosSpinnerStateChanged
        // TODO add your handling code here:
        Double total = Double.valueOf((Integer) menorSpinner.getValue() * 5) + ((Integer) adultosSpinner.getValue() * 7.25);
        totalPanel.setText("$ " + String.valueOf(total));
    }//GEN-LAST:event_adultosSpinnerStateChanged

    private void horarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioComboBoxActionPerformed
        
        //Crea dos variables para hacer la asignacion de Salas.
        String nombre = peliculasComboBox.getSelectedItem().toString();
        String horario = horarioComboBox.getSelectedItem().toString();
        String salaNum = String.valueOf(random.nextInt(6));
        
        if("0".equals(salaNum)) 
            salaNum = "1";
        
        salaPane.setText("Sala " + salaNum);
        
       
      
            
            
            
        
        
        
        
        
        
        
    }//GEN-LAST:event_horarioComboBoxActionPerformed

    private void ventasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasButtonActionPerformed
        // TODO add your handling code here:
        int boletosTotales = 0;
        double ventasFinal = 0.0;
        
        for(ventasTotales venta : ventas) {
            //suma todos los boletos
            boletosTotales += venta.getBoletos();
            
            //suma el total de las ventas
            ventasFinal += venta.getTotalVenta();
        }
        
        System.out.println("\nEl dia de hoy, se han vendido " + boletosTotales + " boletos por un total de $" + ventasFinal);
        System.out.println("\nLa ultima venta realizada es de " + ventas.peek().getBoletos() + " boletos por un total de $" + ventas.peek().getTotalVenta());
        
        
        
    }//GEN-LAST:event_ventasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taquillaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taquillaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taquillaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taquillaCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taquillaCine().setVisible(true);
            }
        });
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner adultosSpinner;
    private javax.swing.JPanel cartelera;
    private javax.swing.JButton continuarButton;
    private javax.swing.JComboBox<String> horarioComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner menorSpinner;
    private javax.swing.JComboBox<String> peliculasComboBox;
    private javax.swing.JTextPane salaPane;
    private javax.swing.JTextField totalPanel;
    private javax.swing.JButton ventasButton;
    // End of variables declaration//GEN-END:variables
}
